# Generated by Django 5.1.2 on 2024-11-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Login.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Login.profile')),
            ],
            options={
                'verbose_name_plural': 'User connection',
                'db_table': 'User connection',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_of_me', to='Login.profile')),
                ('myfollowers', models.ManyToManyField(blank=True, related_name='my_followers', to='Login.profile')),
            ],
            options={
                'verbose_name_plural': "User Follower's",
                'db_table': "User Follower's",
            },
        ),
    ]
