# Generated by Django 5.1.2 on 2024-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='main_img',
            field=models.BooleanField(default=False),
        ),
    ]
