# Generated by Django 5.1.2 on 2024-11-26 16:38

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_comment_comment_text_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=Main.models.upload_image),
        ),
    ]
