# Generated by Django 5.1.2 on 2024-11-19 18:28

import Main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_profile_user'),
        ('Main', '0004_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=Main.models.upload_image),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_upload_date', models.DateTimeField(auto_now_add=True)),
                ('story', models.ImageField(blank=True, upload_to=Main.models.upload_image)),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_story', to='Login.profile')),
            ],
            options={
                'verbose_name_plural': 'Story',
                'db_table': 'Story',
            },
        ),
    ]
